# Generated by Django 5.1.15 on 2026-08-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='storage_path',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
