# Generated by Django 5.2.17 on 2026-08-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_document_storage_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_requested', 'Resubmission Requested')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AddIndex(
            model_name='kycapplication',
            index=models.Index(fields=['applicant', 'status'], name='kyc_app_applicant_status_idx'),
        ),
    ]
