# Generated by Django 6.0.8 on 2026-08-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_kycapplication_status_created_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('document_uploaded', 'Document Uploaded'), ('document_removed', 'Document Removed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_requested', 'Resubmission Requested')], max_length=30),
        ),
    ]
